### ISSUE TITLE
Unable to save Projects that contain invalid XML characters

### ISSUE THREAD

**Issue by mistresseve666** [NetOfficeFw/LateBindingApi.CodeGenerator#2]
I am unable to use Save Project on Libraries that contain certain ASCII values, such as null characters, in Constants. A `System.ArgumentException` Exception with Text: `hexadecimal value 0x00 is an invalid character.` is raised on save. This appears to be coming from the `ToString()` method of the XML object.

The following Library is a good example:

Name: Visual Basic for Applications
Version: 6.0
Base: win32
Path: C:\Windows\SysWow64\MSVBVM60.DLL

**Comment by jozefizso** [comment]
The Component Analyzer does not correctly handle default value of a constant `vbNullChar` which is '\0' (NULL character in .NET). This value cannot be serialized into XML file.

Invalid XElement:
```
<Member Name="vbNullChar" Type="string" Value="\0">
  <RefLibraries>
    <Ref Key="_x0032_b9a0a69-f203-4e5d-90b2-558eeab8d6af" />
  </RefLibraries>
</Member>
```

Previous XElement:
```
<Member Name="vbNullString" Type="string" Value="">
  <RefLibraries>
    <Ref Key="_x0032_b9a0a69-f203-4e5d-90b2-558eeab8d6af" />
  </RefLibraries>
</Member>
```

Next XElement:
```
<Member Name="vbCrLf" Type="string" Value="&#xD;&#xA;">
  <RefLibraries>
    <Ref Key="_x0032_b9a0a69-f203-4e5d-90b2-558eeab8d6af" />
  </RefLibraries>
</Member>
```

**Comment by jozefizso** [comment]
Fixed.
